IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'nrt_contact' and xtype = 'U')
CREATE TABLE dbo.nrt_contact
(
    CONTACT_UID                       bigint,
    ADD_TIME                          datetime NULL,
    ADD_USER_ID                       bigint NULL,
    CONTACT_ENTITY_EPI_LINK_ID        varchar(4000) NULL,
    CONTACT_ENTITY_PHC_UID            bigint NULL,
    CONTACT_ENTITY_UID                bigint NULL,
    CTT_REFERRAL_BASIS                varchar(4000) NULL,
    CTT_STATUS                        varchar(4000) NULL,
    CTT_DISPO_DT                      datetime NULL,
    CTT_DISPOSITION                   varchar(4000) NULL,
    CTT_EVAL_COMPLETED                varchar(4000) NULL,
    CTT_EVAL_DT                       datetime NULL,
    CTT_EVAL_NOTES                    varchar(2000) NULL,
    CTT_GROUP_LOT_ID                  varchar(4000) NULL,
    CTT_HEALTH_STATUS                 varchar(4000) NULL,
    CTT_INV_ASSIGNED_DT               datetime NULL,
    CTT_JURISDICTION_NM               varchar(4000) NULL,
    CTT_NAMED_ON_DT                   datetime NULL,
    CTT_NOTES                         varchar(2000) NULL,
    CTT_PRIORITY                      varchar(4000) NULL,
    CTT_PROCESSING_DECISION           varchar(4000) NULL,
    CTT_PROGRAM_AREA                  varchar(4000) NULL,
    CTT_RELATIONSHIP                  varchar(4000) NULL,
    CTT_RISK_IND                      varchar(4000) NULL,
    CTT_RISK_NOTES                    varchar(2000) NULL,
    CTT_SHARED_IND                    varchar(4000) NULL,
    CTT_SYMP_IND                      varchar(4000) NULL,
    CTT_SYMP_NOTES                    varchar(2000) NULL,
    THIRD_PARTY_ENTITY_PHC_UID        bigint NULL,
    THIRD_PARTY_ENTITY_UID            bigint NULL,
    CTT_SYMP_ONSET_DT                 datetime NULL,
    CTT_TRT_COMPLETE_IND              varchar(4000) NULL,
    CTT_TRT_END_DT                    datetime NULL,
    CTT_TRT_INITIATED_IND             varchar(4000) NULL,
    CTT_TRT_NOT_COMPLETE_RSN          varchar(4000) NULL,
    CTT_TRT_NOT_START_RSN             varchar(4000) NULL,
    CTT_TRT_NOTES                     varchar(2000) NULL,
    CTT_TRT_START_DT                  datetime NULL,
    LAST_CHG_TIME                     datetime NULL,
    LAST_CHG_USER_ID                  bigint NULL,
    LOCAL_ID                          varchar(50) NULL,
    NAMED_DURING_INTERVIEW_UID        bigint NULL,
    PROGRAM_JURISDICTION_OID          bigint NULL,
    RECORD_STATUS_CD                  varchar(4000) NULL,
    RECORD_STATUS_TIME                datetime NULL,
    SUBJECT_ENTITY_EPI_LINK_ID        varchar(4000) NULL,
    SUBJECT_ENTITY_PHC_UID            bigint NULL,
    SUBJECT_ENTITY_UID                bigint NULL,
    PROG_AREA_CD                      varchar(20) NULL,
    JURISDICTION_CD                   varchar(20) NULL,
    VERSION_CTRL_NBR                  smallint NULL,
    CONTACT_EXPOSURE_SITE_UID         bigint NULL,
    PROVIDER_CONTACT_INVESTIGATOR_UID bigint NULL,
    DISPOSITIONED_BY_UID              bigint NULL,
    refresh_datetime                  datetime2(7) GENERATED ALWAYS AS ROW START      NOT NULL,
    max_datetime                      datetime2(7) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
    PERIOD FOR SYSTEM_TIME (refresh_datetime, max_datetime)
);