IF NOT EXISTS (SELECT 1 FROM sysobjects WHERE name = 'nrt_ldf_data' and xtype = 'U')
CREATE TABLE dbo.nrt_ldf_data (
          ldf_uid                           bigint                                          NOT NULL,
          business_object_uid               bigint                                          NOT NULL,
          active_ind                        varchar(20)                                     NULL,
          ldf_meta_data_add_time            datetime                                        NULL,
          admin_comment                     varchar(300)                                    NULL,
          ldf_meta_data_business_object_nm  varchar(100)                                    NULL,
          category_type                     varchar(50)                                     NULL,
          cdc_national_id                   varchar(50)                                     NULL,
          class_cd                          varchar(50)                                     NULL,
          code_set_nm                       varchar(256)                                    NULL,
          condition_cd                      varchar(10)                                     NULL,
          condition_desc_txt                varchar(100)                                    NULL,
          data_type                         varchar(50)                                     NULL,
          deployment_cd                     varchar(10)                                     NULL,
          display_order_nbr                 bigint                                          NULL,
          field_size                        varchar(10)                                     NULL,
          label_txt                         varchar(300)                                    NULL,
          ldf_page_id                       varchar(50)                                     NULL,
          required_ind                      char(1)                                         NULL,
          state_cd                          varchar(10)                                     NULL,
          validation_txt                    varchar(50)                                     NULL,
          validation_jscript_txt            varchar(3000)                                   NULL,
          record_status_time                datetime                                        NULL,
          record_status_cd                  varchar(20)                                     NULL,
          custom_subform_metadata_uid       bigint                                          NULL,
          html_tag                          varchar(50)                                     NULL,
          import_version_nbr                bigint                                          NULL,
          nnd_ind                           char(1)                                         NULL,
          ldf_oid                           varchar(50)                                     NULL,
          ldf_meta_data_version_ctrl_num    bigint                                          NULL,
          nbs_question_uid                  bigint                                          NULL,
          ldf_data_field_add_time           datetime                                        NULL,
          ldf_field_data_business_object_nm varchar(50)                                     NOT NULL,
          ldf_data_last_chg_time            datetime                                        NULL,
          ldf_value                         varchar(2000)                                   NULL,
          ldf_field_data_version_ctrl_num   bigint                                          NULL,
          ldf_column_type                   varchar(50)                                     NULL,
          metadata_record_status_time       datetime                                        NULL,
          metadata_record_status_cd         varchar(20)                                     NULL,
          refresh_datetime                  datetime2(7) GENERATED ALWAYS AS ROW START      NOT NULL,
          max_datetime                      datetime2(7) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
          PERIOD FOR SYSTEM_TIME (refresh_datetime, max_datetime)

      );