spring:
  kafka:
    input:
      topic-name-phc: nbs_Public_health_case
      topic-name-ntf: nbs_Notification
      topic-name-int: nbs_Interview
      topic-name-ctr: nbs_CT_contact
    output:
      topic-name-reporting: nrt_investigation
      topic-name-confirmation: nrt_investigation_confirmation
      topic-name-observation: nrt_investigation_observation
      topic-name-notifications: nrt_investigation_notification
      topic-name-page-case-answer: nrt_page_case_answer
      topic-name-case-management: nrt_investigation_case_management
      topic-name-interview: nrt_interview
      topic-name-interview-answer: nrt_interview_answer
      topic-name-interview-note: nrt_interview_note
      topic-name-rdb-metadata-columns: nrt_metadata_columns
      topic-name-contact: nrt_contact
      topic-name-contact-answer: nrt_contact_answer
    dlq:
      retry-suffix: _retry
      dlq-suffix: _dlt

    group-id: ${KAFKA_CONSUMER_APP:investigation-reporting-consumer-app}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    consumer:
      max-retry: 3
      maxPollIntervalMs: 300000
      enable-auto-commit: false
    admin:
      auto-create: true
  application:
    name: investigation-reporting-service
  datasource:
    password: ${DB_PASSWORD:-fake.fake.fake.1234}
    username: ${DB_USERNAME:-sa}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DB_ODSE_URL:jdbc:sqlserver://localhost:1433;databaseName=:NBS_ODSE;encrypt=true;trustServerCertificate=true;}
    odse:
      url: ${DB_ODSE_URL:jdbc:sqlserver://localhost:1433;databaseName=:NBS_ODSE;encrypt=true;trustServerCertificate=true;}
    rdb:
      url: ${DB_RDB_URL:jdbc:sqlserver://localhost:1433;databaseName=:RDB;encrypt=true;trustServerCertificate=true;}
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
featureFlag:
  phc-datamart-enable: ${FF_PHC_DM_ENABLE:false}
  bmird-case-enable: ${FF_BMIRD_CASE_ENABLE:false}
  contact-record-enable: ${FF_CONTACT_RECORD_ENABLE:false}
server:
  port: '8093'